Repository wecode-bootcamp-korea/21-1st-gonggol-frontend, pull requests merged in 2021-06, with the labels that each got.

#4 [21기 이도윤] 로그인 레이아웃 구현 완료
  src/Pages/Join/Join.js
  src/Pages/Join/Join.scss
  src/Pages/Login/InputBox/InputBox.js
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
Labels: Status: 리뷰 요청

#2 [21기 이도윤]Modify: 회원가입 레이아웃,기능 구현 ,서버통신완료
  src/Pages/Join/CheckBox/CheckBox.js
  src/Pages/Join/InputBox/InputBox.js
  src/Pages/Join/Join.js
  src/Pages/Join/Join.scss
Labels: Status: 수정 요청

#7 [21기 김지민] config 추가 및 링크 등 세부 사항 보완
  src/Component/Header/Header.js
  src/Pages/Category/Category.js
  src/Pages/Join/Join.js
  src/Pages/Join/Join.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Main/Main.js
  src/Pages/Main/NewItem.js
  src/Pages/Product/Product.js
  src/config.js
Labels: Status: Accepted
